language: node_js
node_js:
  - 10
  - 12
  - 13

install: "npm i"
script: "npm run test-and-report-coverage"

deploy:
  provider: npm
  email: "hi@james.engineering"
  api_key:
    secure: "SbUg+iZEO3lF7JgFsYGR7fXvuj3Wfvl+j8AyD99N3fBfajIzYrt0jNbyfk97JeGp2uC7xwvMKk9mQBHaMdW31WAGsEa4ex8vZyagGSYsZxHbpHdHGGi9Qi3rz4OUUbKe6h5wHkSyY2HxqslSm52FRJmEik6DPsBy7UqAC7JtRlM8tZlYjv5nwd6xnVJMcJ7qz4OGWp4b8/T1wXv9M93vxmlEmUDg2bdsLFuIqlRy/ORR8v76p+Lx9SSKeyTsSqYf1UNCu1rC3CVnIxHSj0EncMU/UJpL/pyQFeuoZ1G14vdNjq1Jbrb/M7dAXahl0ALywtjVfr5Wk6Va/sDNRniyT82OTio2T3MR867vGa5fD6ssmYCUcujf4MLqMV05iEKCiLv1TjINytH58229dDrZNHLr05Sv+5IBVmMVlZwmFOIW/RIcOBXFPvGmGiFBCOp8KEBBtKVimWqB6WIuRkmE4YM3BvM/yIs2N/bKXmgW3iuvfqLmdDzf591AsGbnOaAaK7jOxikO1RztpHOIEXp7/TtbmKz30kxQRMHF2RFZGg4ZhuqyZTNYTsFgbLj60jwESdm+p+4Y8PC8bR3KF7VYq8pkgV4UYVM/Nu2ZrWqfgJcN+8dhtloXM4O5lD6elO9KhBPsNvu8XuSn+u/U37AurniajPkom0QPxlp9rVWEqPE="

  on:
    tags: true
